# Generated by Django 4.2 on 2023-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField(max_length=5000)),
                ("starting_bid", models.FloatField()),
                ("image_url", models.URLField()),
                ("category", models.CharField(max_length=64)),
            ],
        ),
    ]
