# Generated by Django 4.2 on 2023-04-23 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("1", "Toys"),
                    ("2", "Cars"),
                    ("3", "Clothing"),
                    ("4", "Furniture"),
                    ("5", "Instruments"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
