# Generated by Django 4.2 on 2023-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
