# Generated by Django 4.2 on 2023-04-26 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_alter_listing_starting_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Toys", "Toys"),
                    ("Cars", "Cars"),
                    ("Clothing", "Clothing"),
                    ("Furniture", "Furniture"),
                    ("Instruments", "Instruments"),
                    ("Animals", "Animals"),
                ],
                max_length=64,
            ),
        ),
    ]
