# Generated by Django 4.2 on 2023-04-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_listing_user_alter_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watched_listing",
            field=models.ManyToManyField(
                related_name="watched_listing", to="auctions.listing"
            ),
        ),
    ]
