# Generated by Django 4.2 on 2023-04-28 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="listing",
            new_name="listing_id",
        ),
    ]
