# Generated by Django 4.2 on 2023-04-28 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0016_rename_listing_bid_listing_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="highest_bid",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
            ),
            preserve_default=False,
        ),
    ]
