# Generated by Django 4.2 on 2023-04-28 09:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0018_alter_listing_highest_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="listing_id",
            new_name="listing",
        ),
        migrations.AddField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="highest_bid",
            field=models.FloatField(
                blank=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000000),
                ],
            ),
        ),
    ]
