# Generated by Django 4.2 on 2023-04-28 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0019_rename_listing_id_bid_listing_bid_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="user",
        ),
    ]
