# Generated by Django 4.2 on 2023-04-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0021_bid_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="created_at",
            new_name="date",
        ),
        migrations.AddField(
            model_name="bid",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-04-26 18:41:56.705751"),
            preserve_default=False,
        ),
    ]
